# Using the latest version of Python
FROM python:3.11.8

# Creating a working directory know as source to store development code and requirements.txt
WORKDIR /src

# Copying all the files from the src directory
COPY src/. .

# Install the necessary python packages
RUN pip install -r requirements.txt

CMD [ "python", "/src/nlp_brush_up.ipynb" ]